  MathJax.Hub.Config({
    tex2jax: { inlineMath: [['$','$'], ['\\(','\\)']],
              displayMath: [ ['$$','$$'], ['\\[','\\]'] ],
              processEscapes: true },
    extensions: ["tex2jax.js","TeX/AMSmath.js","TeX/AMSsymbols.js"],
    jax: ["input/TeX","output/HTML-CSS"],
    TeX: {
      Macros: {
      
      
        K: '\\mathds K',
        C: '\\mathds C',
        R: '\\mathds R',
        Q: '\\mathds Q',
        Z: '\\mathds Z',
        N: '\\mathds N',
        F: '\\mathds F',
        A: '\\mathds A',
        I: '\\mathds I',
        U: '\\mathds U',
        L: '\\mathds L',
        k: '\\mathds k',
        H: '\\mathds H',
        P: '\\mathds P',
        mathds: '\\mathbb',
        cA: '\\mathscr A',
        cC: '\\mathscr C',
        cE: '\\mathscr E',
        cF: '\\mathscr F',
        cG: '\\mathscr G',
        cH: '\\mathscr H',
        cL: '\\mathscr L',
        cP: '\\mathscr P',
        cR: '\\mathscr R',
        cS: '\\mathscr S',
        cK: '\\mathscr K',
        cM: '\\mathscr M',
        CA: '\\mathcal A',
        CC: '\\mathcal C',
        CN: '\\mathcal N',
        CO: '\\mathcal O',
        CK: '\\mathcal K',
        CM: '\\mathcal M',
        ga: '\\mathfrak a',
        gb: '\\mathfrak b',
        gm: '\\mathfrak m',
        gf: '\\mathfrak f',
        gp: '\\mathfrak p',
        gu: '\\mathfrak u',
        gP: '\\mathfrak P',
        gM: '\\mathfrak M',
        gS: '\\mathfrak S',
        leq: '\\leqslant',
        geq: '\\geqslant',
        isomto: '{\\mathop{\\longrightarrow}^\\sim}',
        floor: ['\\lfloor #1 \\rfloor', 1],
        ceil: ['\\lceil #1 \\rceil', 1],
        float: ['\\{ #1 \\}', 1],
        abs: ['\\left\\lvert #1\\right\\rvert', 1],
        set: ['\\left\\{ #1\\right\\}', 1],
        card: ['\\#{ #1}', 1],
        prodscal: ['\\langle #1 \\rangle', 1],
        span: ['\\langle #1 \\rangle', 1],
        invMel: ['\\mathscr{M}^{-1}\\left[ #1 \\right]', 1],
        kronecker: ['\\left(\\frac{ #1}{ #2}\\right)', 2],
        norm: ['\\left\\lVert #1\\right\\rVert', 1],
        d: '\\,\\mathrm{d}',
        ds: '\\,\\mathrm{d}s',
        dt: '\\,\\mathrm{d}t',
        dx: '\\,\\mathrm{d}x',
        dy: '\\,\\mathrm{d}y',
        dz: '\\,\\mathrm{d}z',
        du: '\\,\\mathrm{d}u',
        dv: '\\,\\mathrm{d}v',
        incGam: '\\Gamma',
        GamR: '\\Gamma_{\\R}',
        GamC: '\\Gamma_{\\C}',
        deffunc: ['\\left\\{\\begin{array}{ccc} #1&\\to&#2\\\\ #3&\\mapsto&#4 \\end{array}\\right.', 4],
      
        im: '\\operatorname{ Im }',
        Frac: '\\operatorname{ Frac }',
        pgcd: '\\operatorname{ pgcd }',
        ppcm: '\\operatorname{ ppcm }',
        argmin: '\\operatorname{ argmin }',
        argmax: '\\operatorname{ argmax }',
        Gl: '\\operatorname{ Gl }',
        Sp: '\\operatorname{ Sp }',
        Sl: '\\operatorname{ Sl }',
        Aff: '\\operatorname{ Aff }',
        Id: '\\operatorname{ Id }',
        trace: '\\operatorname{ trace }',
        rank: '\\operatorname{ rg }',
        Com: '\\operatorname{ Com }',
        vect: '\\operatorname{ vect }',
        Aut: '\\operatorname{ Aut }',
        erfc: '\\operatorname{ erfc }',
        Lw: '\\operatorname{ L_W }',
        Lx: '\\operatorname{ L_X }',
        Res: '\\operatorname{ Res }',
        Log: '\\operatorname{ Log }',
        asinh: '\\operatorname{ asinh }',
        acosh: '\\operatorname{ acosh }',
        atanh: '\\operatorname{ atanh }',
        End: '\\operatorname{ End }',
        Gal: '\\operatorname{ Gal }',
        Hom: '\\operatorname{ Hom }',
        Cl: '\\operatorname{ Cl }',
        Frob: '\\operatorname{ Frob }',
        Norm: '\\operatorname{ Norm }',
        Div: '\\operatorname{ Div }',
        Pic: '\\operatorname{ Pic }',

      }
    },
  });
